services:
  - type: web
    name: roberthood
    env: ruby
    runtime: ruby-3.4.4
    region: illinois
    plan: free
    buildCommand: "./build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: FINANCIAL_MODELING_API_KEY
        sync: false
      - key: NEWS_API_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: NODE_VERSION
        value: "18.17.0"
      - key: RUBY_VERSION
        value: "3.4.4"
      - key: REACT_APP_FIREBASE_API_KEY
        sync: false
      - key: REACT_APP_FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: REACT_APP_FIREBASE_APP_ID
        sync: false
      - key: REACT_APP_FIREBASE_MEASUREMENT_ID
        sync: false