# Firebase-only configuration
# This app uses Firebase for all data storage
# No traditional database adapter needed

default: &default
  adapter: nulldb
  schema_search_path: public

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
